on:
  push:
    paths:
      - '.github/workflows/change-images.yml'
      - 'Dockerfile'
env:
  REGISTRY_URL: ghcr.io
  REGISTRY_PREFIX: ghcr.io/${{github.repository}}
  IMG_GOLANG: golang:1.15-alpine
jobs:
  golang-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.ghcr_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - uses: actions/checkout@v2
      - run: docker pull $REGISTRY_PREFIX/$IMG_GOLANG || echo "no image"
      - run: docker build --tag=$REGISTRY_PREFIX/$IMG_GOLANG --target=env --build-arg BASE_IMG=$IMG_GOLANG --cache-from=$REGISTRY_PREFIX/$IMG_GOLANG .
      - run: docker images
      - run: docker push $REGISTRY_PREFIX/$IMG_GOLANG
